### ISSUE TITLE
Get a MWE (minimal working exemple) in the README.md to demonstrate basic features

### ISSUE THREAD

**Issue by samusz** [GenieFramework/StippleLatex.jl#8]
I feel the use of LaTeX should be encouraged with this package enabling KaTeX in Genie. 

Also, I would like to try this out, but I am not sure how to use it in my Genie app. 

So a MWE would be nice in the README. 

(A detailed documentation would simply follow, I guess).

**Comment by hhaensel** [comment]
@essenciary 
We could paste my example from the [latest PR](https://github.com/GenieFramework/StippleLatex.jl/pull/11#issuecomment-1435660528) in the MWE, what do you think?

**Comment by essenciary** [comment]
@hhaensel agree

Just a bit concerned about the `route` section. The `global` doesn't look like good practice. Would be good to "compact" the code in `route` and remove the global. 

<img width="231" alt="image" src="https://user-images.githubusercontent.com/11292378/220033846-d920a95c-8598-42ab-8538-4067977202b8.png">

Something like this should work too? 

```julia
route("/") do
    page(@init(), ui()) |> html
end
```

**Comment by hhaensel** [comment]
Have a look at the README.md

**Comment by hhaensel** [comment]
@samusz can we close this?

**Comment by samusz** [comment]
Sure !
